### ISSUE TITLE
Some questions about reimplement 

### ISSUE THREAD

**Issue by XWalways** [D-X-Y/TAS#3]
I just reimplement yours paper's idea,but i have some questions: when sampling two channel choices:one is the largest probability choice,anthor is sampled randomly(Less than the former)?
if it's randomly sample,how to make it differentiable?

**Comment by D-X-Y** [comment]
@XWalways Thanks for your interests. Please refer https://github.com/D-X-Y/NAS-Projects for my released codes. I just move our codes to https://github.com/D-X-Y/NAS-Projects and will close this repo.
